# Generated by Django 4.1.2 on 2022-10-16 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_topic_room_host_message_room_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
